# Generated by Django 4.0.6 on 2022-07-25 21:25

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('vin', models.CharField(db_index=True, max_length=17, primary_key=True, serialize=False, unique=True)),
                ('category', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'European Elite Classic'), (1, 'US Retro'), (2, 'European Legend'), (3, 'Fully Restored Oldtimer'), (4, 'US Muscle Car'), (5, 'Offroad Classic'), (6, 'Asian Legends'), (7, 'Rare Supercar'), (8, 'Deep Tuned Custom'), (9, 'European Racing Classics'), (10, ' Other')], default=10)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('production_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(1900)], verbose_name='year')),
                ('condition', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Excellent'), (1, 'Very Good'), (2, 'Good'), (3, 'Satisfactory'), (4, 'Poor'), (5, 'Out of order'), (6, 'Other')], default=6, null=True)),
                ('mileage', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3000000)])),
                ('seats', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)])),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None)),
                ('transmission', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Manual'), (1, 'Automatic'), (2, 'Other')], default=2, null=True)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='media/vehicle')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='telegram_bot.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='telegram_bot.user')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='telegram_bot.vehicle')),
            ],
            options={
                'db_table': 'tg_search_history',
            },
        ),
    ]
